Update: add MIT license to readme file
Tech-Sisters-Kenya/todo_sample_app pull request #30
Opened 2024-12-04 22:18 UTC by ASLawan

Added MIT license to the readme file

PS: I hope the repo is not restricted only to females. If so, I am sorry

2025-01-11 06:02 UTC, cesswairimu requested changes
hello @ASLawan, thanks for  working of this. 
Please update the year and its good to merge. Thanks

2025-01-11 06:02 UTC, cesswairimu commented on README.md
> +Copyright (c) 2024 Tech Sisters Kenya
please update the year

2025-01-11 06:09 UTC, ASLawan commented
Thank you for your reply. I will do just that.

On Sat, Jan 11, 2025, 7:02 AM Cess ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> hello @ASLawan <https://github.com/ASLawan>, thanks for working of this.
> Please update the year and its good to merge. Thanks
> ------------------------------
>
> In README.md
> <https://github.com/Tech-Sisters-Kenya/todo_sample_app/pull/30#discussion_r1911905281>
> :
>
> > \ No newline at end of file
> +3. You should be able to view the app on http://127.0.0.1:8080 or localhost:8080 from your browser
> +
> +## MIT License
> +
> +MIT License
> +
> +Copyright (c) 2024 Tech Sisters Kenya
>
> please update the year
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Tech-Sisters-Kenya/todo_sample_app/pull/30#pullrequestreview-2544566281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBD3K4GRBVKPYL7P35FT5O32KCXXPAVCNFSM6AAAAABTBFBVASVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBUGU3DMMRYGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-02-05 03:57 UTC, cesswairimu approved these changes
Thanks again @ASLawan, will merge now :rocket:

2025-02-05 03:58 UTC, merged